### ISSUE TITLE
Problème script

### ISSUE THREAD

**Issue by frenchqwerty** [kayofeld/script-installation-ordinateur-epitech#15]
Bonjour,

J'ai clone le repo, je fais le commande : ./install yassir.jabbari@epitech.eu
Et il ne reconnait l'argument avec mon login, donc je le mets entre guillemet et ça fait exactement pareil.
Donc je fais comme l'exemple : ./install <yassir.jabbari@epitech.eu>
Et là il me met : -bash: syntax error near unexpected token `newline'
Donc comment je fais ? J'ai besoin de donner les droits sur un repo et je suis sous windows avec le Bash ubuntu d'installer, avant de redump ça fonctionnait mais là non...

Merci d'avance !

**Comment by kayofeld** [comment]
Bonjour,

Si j'ai bien compris, l'environnement d'éxecution est le sous-système linux pour windows, donc une execution à l'intérieur de Bash pour Ubuntu pour Windows ?

En reproduisant cet environnement, j'ai pu lancer le script sans problème, et sans guillemets.
Y a-t-il  eu des soucis avec d'autres scripts bash ?
Est-ce que le script a été altéré ?

En lançant la commande:
```md5sum install```
l'output est-t-il bien:
```68ce96624f261bfd034046531eff0ffc  install``` ?

**Comment by kayofeld** [comment]
N'ayant pas eu de réponse depuis 25 jours, le ticket est considéré comme clos.
