### ISSUE TITLE
Installation fails in OpenSuse (Windows Linux Subsystem)

### ISSUE THREAD

**Issue by hAz4rd0uS** [kayofeld/script-installation-ordinateur-epitech#18]
Hi,

The installation fails on OpenSuse (in Windows Linux Subsystem) because of the -y option in both zypper commands (zypper update and zypper install).
To fix it, you'll have to delete the -y option and validate each installation step by typing "y" on the prompt.

**Comment by bew** [comment]
Is it still needed @hAz4rd0uS ?

**Comment by hAz4rd0uS** [comment]
Not anymore for me, thx for asking :)

Pierrick MARTELLIERE
5ème année {EPITECH.}
Développeur web et mobile
p.martelliere@gmail.com
06 95 05 57 49
